#!/usr/bin/env bash
#display content of /etc/passwd
IFS=':'
while read -r USERNAME PASSWORD USERID GROUP_ID USERIDINFO HOME_DIRECTORY SHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < /etc/passwd
