#!/usr/bin/env bash
# display best schooll 8 times except 4th and 8th iteration
i=0
while ((i<10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
