#!/usr/bin/env bash
# displays numbers from 1 to 20 with exceptions on4, 9 and 17
i=1
while ((i<=21))
do
	echo $i
	case "$i" in
		4)echo "bad luck from China";;
		9)echo "bad luck from Japan";;
		17)echo "bad luck from Italy";;
		esac
	((i++))
done
