#!/usr/bin/env bash
# display to infinity and beyond indefinitely
# sleep 2 iteration
# I am invincinle!!! when receiving SIGTERM signal
trap 'echo "I am invincible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
